
insert ignore into code_category (id, description)
values
(1, 'Administration, documents and attachments'),
(2, 'Allergy and adverse drug reactions'),
(3, 'Allergy and adverse reactions'),
(4, 'Biochemistry'),
(5, 'Biological values'),
(6, 'Body structure'),
(7, 'Care episode outcome'),
(8, 'Conditions, operations and procedures'),
(9, 'Cytology/Histology'),
(10, 'Dental disorder'),
(11, 'Dental finding'),
(12, 'Dental procedure'),
(13, 'Diagnostics'),
(14, 'Discharged from service'),
(15, 'EMIS Qualifier'),
(16, 'Ethnicity'),
(17, 'Family history'),
(18, 'Haematology'),
(19, 'Health management, screening and monitoring'),
(20, 'HMP'),
(21, 'Immunisations'),
(22, 'Immunology'),
(23, 'Intervention category'),
(24, 'Intervention target'),
(25, 'Investigation requests'),
(26, 'KC60'),
(27, 'Marital status'),
(28, 'Microbiology'),
(29, 'Nationality'),
(30, 'Nursing problem'),
(31, 'Nursing problem domain'),
(32, 'Obstetrics and Birth'),
(33, 'Pathology specimen'),
(34, 'social-history'),
(35, 'Planned dental intervention'),
(36, 'Problem rating scale for outcomes'),
(37, 'Procedure code'),
(38, 'Radiology'),
(39, 'Reason for care'),
(40, 'Referral'),
(41, 'Referral activity'),
(42, 'Referral rejected'),
(43, 'Referral withdrawn'),
(44, 'Regiment'),
(45, 'Religion'),
(46, 'Symptoms and Findings'),
(47, 'Trade/Branch'),
(48, 'Main language');

